apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: azuredns-credentials
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: platform-secret-store
    kind: ClusterSecretStore
  target:
    name: azuredns-credentials
  data:
  - secretKey: clientSecret
    remoteRef:
      key: platform-cloud-client-secret
