apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-entra-id
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: platform-secret-store
    kind: ClusterSecretStore
  target:
    name: argocd-entra-id
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
  - secretKey: clientID
    remoteRef:
      key: platform-authentication-client-id
  - secretKey: clientSecret
    remoteRef:
      key: platform-authentication-client-secret
