apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configs/namespace.yaml
  - configs/rbac.yaml
  - configs/acr-credentials.yaml
  - configs/api-key.yaml
  - configs/deployment.yaml
  - configs/ingress.yaml
  - configs/networkpolicy.yaml
