apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-app
  namespace: backstage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: platform-secret-store
    kind: ClusterSecretStore
  target:
    name: github-app
  data:
  - secretKey: privateKey
    remoteRef:
      key: platform-github-app-private-key
  - secretKey: clientSecret
    remoteRef:
      key: platform-github-app-client-secret