apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: terraform-azure-creds
  namespace: kratix-workloads
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: platform-secret-store
    kind: ClusterSecretStore
  target:
    name: terraform-azure-creds
  data:
  - secretKey: client_id
    remoteRef:
      key: platform-cloud-client-id
  - secretKey: client_secret
    remoteRef:
      key: platform-cloud-client-secret
  - secretKey: tenant_id
    remoteRef:
      key: platform-cloud-tenant-id
  - secretKey: subscription_id
    remoteRef:
      key: platform-cloud-subscription-id
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: terraform-backend-config
  namespace: kratix-workloads
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: platform-secret-store
    kind: ClusterSecretStore
  target:
    name: terraform-backend-config
  data:
  - secretKey: resource_group_name
    remoteRef:
      key: platform-terraform-backend-rg
  - secretKey: storage_account_name
    remoteRef:
      key: platform-terraform-backend-storage-account
  - secretKey: container_name
    remoteRef:
      key: platform-terraform-backend-container
