apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slack-webhook
  namespace: kratix-workloads
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: platform-secret-store
    kind: ClusterSecretStore
  target:
    name: slack-webhook
  data:
  - secretKey: url
    remoteRef:
      key: platform-slack-webhook-url