apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configs/core/namespace.yaml
  - configs/core/networkpolicy.yaml
  - configs/core/azure-creds.yaml
  - configs/providers/kubernetes.yaml
  - configs/providers/azure-keyvault.yaml
  - configs/providers/azure-storage.yaml
  