apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: platform-secret-store
spec:
  provider:
    azurekv:
      vaultUrl: "https://teknologi-eur1-kv.vault.azure.net"
      tenantId: "99f9af3a-fd8b-41ec-b487-483a0c562b5c"
      authType: ServicePrincipal
      authSecretRef:
        clientId:
          name: azure-kv-credentials
          namespace: external-secrets
          key: clientId
        clientSecret:
          name: azure-kv-credentials
          namespace: external-secrets
          key: clientSecret